- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create a username for tomcat
      user:
        name: tomcatadm
        group: users
        shell: /bin/bash
        home: /home/tomcat

    - name: create a directory for apache tomcat
      file:
        path: /opt/oracle
        owner: tomcatadm
        group: users
        state: present
        mode: 0755
